[workspace]
[package]
version = "0.1.0"
name = "appattest-circuits-script"
edition = "2021"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1", features = ["neon"] }

[[bin]]
name = "compressed"
path = "bin/compressed.rs"